// Generated by bin/sdk_contract.dart. Do not edit.
export const sdkAPI = {
  entry: 'package:dartnative_camera/dartnative_camera.dart',
  declarationsDigest: 'c0095038e7cc50e7dee22f3920f5a28edeba6bd0e3dcd14b1e3704280bb201bb',
  files: {
    'dartnative_camera.dart': '1c1e760d19e030b582b848dc9e649b32ddc9b9c27af5b0c06397e369b31dbc62',
    'src/camera_controller.dart':
      '1058de0b3ab861b2f25b07c6cda0d6669277d617ca901a7ea366cdbe5f58d674',
    'src/camera_ffi_bindings.dart':
      '38867458b10ee98719387a95c2ccc981f5f8c3dcdf0c7e4d57fb61f70acb793c',
    'src/camera_preview.dart': '6d6d92a7e46d2acd10085c88654b6845b26bfecdb2c0d56afc7efab8a0a25606',
    'src/camera_types.dart': 'c3555c4107e65f4f7e91fc0d41ddbe76a3c50450449e553cac9ecf8b08a2095b',
    'src/dartnative_camera.dart':
      'b7eb53e990d554cd84dbda1b86bac4325ed08ee9b603286b73330c53d63069c0',
  },
  symbols: {
    CameraController: {
      kind: 'class',
      file: 'src/camera_controller.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'description',
              named: false,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'resolutionPreset',
              named: false,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'enableAudio',
              named: true,
              required: false,
              type: null,
              default: 'true',
            },
            {
              name: 'videoQuality',
              named: true,
              required: false,
              type: null,
              default: 'VideoQuality.hd',
            },
            {
              name: 'videoAspectRatio',
              named: true,
              required: false,
              type: null,
              default: 'VideoAspectRatio.defaultRatio',
            },
            {
              name: 'videoBitRateBps',
              named: true,
              required: false,
              type: null,
              default: '0',
            },
          ],
          offset: 1710,
        },
      },
    },
    CameraDescription: {
      kind: 'class',
      file: 'src/camera_types.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'name',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'lensDirection',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'sensorOrientation',
              named: true,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 3480,
        },
      },
    },
    CameraException: {
      kind: 'class',
      file: 'src/camera_types.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'code',
              named: false,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'description',
              named: false,
              required: false,
              type: null,
              default: null,
            },
          ],
          offset: 6205,
        },
      },
    },
    CameraFfiBindings: {
      kind: 'class',
      file: 'src/camera_ffi_bindings.dart',
      base: null,
      constructors: {},
    },
    CameraImage: {
      kind: 'class',
      file: 'src/camera_types.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'format',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'width',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'height',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'bytes',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'timestampNs',
              named: true,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 5395,
        },
      },
    },
    CameraLensDirection: {
      kind: 'enum',
      file: 'src/camera_types.dart',
      values: ['front', 'back', 'external'],
    },
    CameraPreview: {
      kind: 'class',
      file: 'src/camera_preview.dart',
      base: 'StatefulWidget',
      constructors: {
        '': {
          parameters: [
            {
              name: 'key',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'controller',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'enablePinchToZoom',
              named: true,
              required: false,
              type: null,
              default: 'true',
            },
            {
              name: 'enableTapToFocus',
              named: true,
              required: false,
              type: null,
              default: 'true',
            },
          ],
          offset: 2323,
        },
      },
    },
    CaptureOrientation: {
      kind: 'enum',
      file: 'src/camera_types.dart',
      values: ['portraitUp', 'portraitDown', 'landscapeLeft', 'landscapeRight'],
    },
    DartNativeCamera: {
      kind: 'class',
      file: 'src/dartnative_camera.dart',
      base: null,
      constructors: {},
    },
    FlashMode: {
      kind: 'enum',
      file: 'src/camera_types.dart',
      values: ['off', 'auto', 'always', 'torch'],
    },
    RecordingEvent: {
      kind: 'class',
      file: 'src/camera_types.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'kind',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'durationUs',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'sizeBytes',
              named: true,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 4485,
        },
      },
    },
    RecordingEventKind: {
      kind: 'enum',
      file: 'src/camera_types.dart',
      values: ['start', 'status', 'pause', 'resume'],
    },
    ResolutionPreset: {
      kind: 'enum',
      file: 'src/camera_types.dart',
      values: ['veryLow', 'low', 'medium', 'high', 'veryHigh', 'ultraHigh', 'max'],
    },
    VideoAspectRatio: {
      kind: 'enum',
      file: 'src/camera_types.dart',
      values: ['defaultRatio', 'ratio4_3', 'ratio16_9'],
    },
    VideoQuality: {
      kind: 'enum',
      file: 'src/camera_types.dart',
      values: ['lowest', 'sd', 'hd', 'fhd', 'uhd', 'highest'],
    },
    registerCameraElementFactory: {
      kind: 'function',
      file: 'src/camera_preview.dart',
      returns: 'void',
      parameters: [],
    },
  },
};
