// Generated by bin/sdk_contract.dart. Do not edit.
export const sdkAPI = {
  entry: 'package:dartnative_google_maps/dartnative_google_maps.dart',
  declarationsDigest: '419db6b2b5fb68bc20472bb1c64514d0870967d2e8a9949e4b844e201e643e8c',
  files: {
    'dartnative_google_maps.dart':
      'a44ed35dd7d3f4c595ea4855e501bf2034def0eb440502529fc30ce76db5a116',
    'src/dartnative_google_maps.dart':
      '99476154fad290fd5f941e28722b30e06b1de566317d6baa7edc34397fcff613',
    'src/maps_ffi_bindings.dart':
      '11577bc200d7be2ca8361e594fd8eca04413bbfad8e23852ef1a860be0e0731e',
  },
  symbols: {
    CameraPosition: {
      kind: 'class',
      file: 'src/dartnative_google_maps.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'latitude',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'longitude',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'zoom',
              named: true,
              required: false,
              type: null,
              default: '10.0',
            },
          ],
          offset: 1164,
        },
      },
    },
    GoogleMaps: {
      kind: 'class',
      file: 'src/dartnative_google_maps.dart',
      base: 'StatefulWidget',
      constructors: {
        '': {
          parameters: [
            {
              name: 'key',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'initialCameraPosition',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'mapType',
              named: true,
              required: false,
              type: null,
              default: 'MapType.normal',
            },
            {
              name: 'zoomGesturesEnabled',
              named: true,
              required: false,
              type: null,
              default: 'true',
            },
            {
              name: 'scrollGesturesEnabled',
              named: true,
              required: false,
              type: null,
              default: 'true',
            },
            {
              name: 'markers',
              named: true,
              required: false,
              type: null,
              default: 'const []',
            },
            {
              name: 'onMapReady',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'onMarkerTap',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'onCameraMove',
              named: true,
              required: false,
              type: null,
              default: null,
            },
          ],
          offset: 3438,
        },
      },
    },
    GoogleMapsElement: {
      kind: 'class',
      file: 'src/dartnative_google_maps.dart',
      base: 'NativeElement',
      constructors: {
        '': {
          parameters: [
            {
              name: 'widget',
              named: false,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 4103,
        },
      },
    },
    GoogleMapsView: {
      kind: 'class',
      file: 'src/dartnative_google_maps.dart',
      base: 'Widget',
      constructors: {
        '': {
          parameters: [
            {
              name: 'key',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'initialCameraPosition',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'mapType',
              named: true,
              required: false,
              type: null,
              default: 'MapType.normal',
            },
            {
              name: 'zoomGesturesEnabled',
              named: true,
              required: false,
              type: null,
              default: 'true',
            },
            {
              name: 'scrollGesturesEnabled',
              named: true,
              required: false,
              type: null,
              default: 'true',
            },
            {
              name: 'markers',
              named: true,
              required: false,
              type: null,
              default: 'const []',
            },
          ],
          offset: 1920,
        },
      },
    },
    LatLng: {
      kind: 'class',
      file: 'src/dartnative_google_maps.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'latitude',
              named: false,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'longitude',
              named: false,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 902,
        },
      },
    },
    MapType: {
      kind: 'enum',
      file: 'src/dartnative_google_maps.dart',
      values: ['none', 'normal', 'satellite', 'terrain', 'hybrid'],
    },
    MapsFFIBindings: {
      kind: 'class',
      file: 'src/maps_ffi_bindings.dart',
      base: null,
      constructors: {},
    },
    Marker: {
      kind: 'class',
      file: 'src/dartnative_google_maps.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'id',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'latitude',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'longitude',
              named: true,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 1460,
        },
      },
    },
    initializeGoogleMapsPlugin: {
      kind: 'function',
      file: 'src/dartnative_google_maps.dart',
      returns: 'void',
      parameters: [],
    },
  },
};
