// Generated by bin/sdk_contract.dart. Do not edit.
export const sdkAPI = {
  entry: 'package:social_sign_in/social_sign_in.dart',
  declarationsDigest: '74d3b678263783b3f3176635a93d8d45e7007beb306c6e73b802e36aa78bf169',
  files: {
    'social_sign_in.dart': '918424ae709c6f8b6e661a51e112a2b5e7f65b61677339fb2bbd3d3190784530',
    'src/apple_id_authorization_scopes.dart':
      '02d11bce2f9f0d5ab1759c0f62d81b6dce22db1e2ee2f8283123448ce73c6fa0',
    'src/authorization_credential_apple_id.dart':
      '310fcab93e6e3a329b5f49dc594e545d42264aa208b7d914a2b6f44531b5bae9',
    'src/google_sign_in.dart': 'e0e6909ef08cc8422a14cbca599e1b4e99aadaca2963f8773af8c0489ef3dd13',
    'src/google_sign_in_account.dart':
      '3ed91bf1d5b4b0d2223e1081fe411879167ea389949fc3c96d4a23efa4c2e993',
    'src/google_sign_in_ffi_bindings.dart':
      '9e53b46c06fb6e6aaff835bd9bd2c093fbceda95f321b1b00ded56a1b4c6d1d6',
    'src/sign_in_with_apple.dart':
      'cc4b3ac905ae232771a1e957dcb5c016602867fdb0907455e4e2edef35335bf5',
    'src/sign_in_with_apple_exception.dart':
      'ecc86ae448073cc5095216d4ab0cdb2bf09891ae95c179d7476dfec722f1342a',
    'src/sign_in_with_apple_ffi_bindings.dart':
      '6dcbebaab0f78492efaef9415440fbdc023e2927d703e5e51ff24590dea8b78b',
  },
  symbols: {
    AppleIDAuthorizationScopes: {
      kind: 'enum',
      file: 'src/apple_id_authorization_scopes.dart',
      values: ['email', 'fullName'],
    },
    AuthorizationCredentialAppleID: {
      kind: 'class',
      file: 'src/authorization_credential_apple_id.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'userIdentifier',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'authorizationCode',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'identityToken',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'givenName',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'familyName',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'email',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'state',
              named: true,
              required: false,
              type: null,
              default: null,
            },
          ],
          offset: 370,
        },
      },
    },
    AuthorizationErrorCode: {
      kind: 'enum',
      file: 'src/sign_in_with_apple_exception.dart',
      values: ['canceled', 'failed', 'invalidResponse', 'notHandled', 'unknown'],
    },
    GoogleSignIn: {
      kind: 'class',
      file: 'src/google_sign_in.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'serverClientId',
              named: true,
              required: false,
              type: null,
              default: null,
            },
          ],
          offset: 1045,
        },
      },
    },
    GoogleSignInAccount: {
      kind: 'class',
      file: 'src/google_sign_in_account.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'email',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'displayName',
              named: true,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'authentication',
              named: true,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 648,
        },
      },
    },
    GoogleSignInAuthentication: {
      kind: 'class',
      file: 'src/google_sign_in_account.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'idToken',
              named: true,
              required: false,
              type: null,
              default: null,
            },
            {
              name: 'accessToken',
              named: true,
              required: false,
              type: null,
              default: null,
            },
          ],
          offset: 280,
        },
      },
    },
    GoogleSignInException: {
      kind: 'class',
      file: 'src/google_sign_in.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'message',
              named: false,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'canceled',
              named: true,
              required: false,
              type: null,
              default: 'false',
            },
          ],
          offset: 268,
        },
      },
    },
    GoogleSignInFFIBindings: {
      kind: 'class',
      file: 'src/google_sign_in_ffi_bindings.dart',
      base: null,
      constructors: {},
    },
    SignInWithApple: {
      kind: 'class',
      file: 'src/sign_in_with_apple.dart',
      base: null,
      constructors: {},
    },
    SignInWithAppleAuthorizationException: {
      kind: 'class',
      file: 'src/sign_in_with_apple_exception.dart',
      base: 'SignInWithAppleException',
      constructors: {
        '': {
          parameters: [
            {
              name: 'message',
              named: false,
              required: true,
              type: null,
              default: null,
            },
            {
              name: 'code',
              named: true,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 612,
        },
      },
    },
    SignInWithAppleException: {
      kind: 'class',
      file: 'src/sign_in_with_apple_exception.dart',
      base: null,
      constructors: {
        '': {
          parameters: [
            {
              name: 'message',
              named: false,
              required: true,
              type: null,
              default: null,
            },
          ],
          offset: 189,
        },
      },
    },
    SignInWithAppleFFIBindings: {
      kind: 'class',
      file: 'src/sign_in_with_apple_ffi_bindings.dart',
      base: null,
      constructors: {},
    },
  },
};
